// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: msgproto/msgdef.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MsgNil MsgType = 0
	MsgType_MsgReq MsgType = 1
	MsgType_MsgRes MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MsgNil",
		1: "MsgReq",
		2: "MsgRes",
	}
	MsgType_value = map[string]int32{
		"MsgNil": 0,
		"MsgReq": 1,
		"MsgRes": 2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgproto_msgdef_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_msgproto_msgdef_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_msgproto_msgdef_proto_rawDescGZIP(), []int{0}
}

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_msgdef_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_msgdef_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_msgproto_msgdef_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_msgdef_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_msgdef_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_msgproto_msgdef_proto_rawDescGZIP(), []int{1}
}

func (x *Res) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_msgproto_msgdef_proto protoreflect.FileDescriptor

var file_msgproto_msgdef_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x64, 0x65,
	0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x17, 0x0a, 0x03,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x17, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x2d,
	0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x73, 0x67,
	0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x10, 0x02, 0x42, 0x07, 0x5a,
	0x05, 0x2e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgproto_msgdef_proto_rawDescOnce sync.Once
	file_msgproto_msgdef_proto_rawDescData = file_msgproto_msgdef_proto_rawDesc
)

func file_msgproto_msgdef_proto_rawDescGZIP() []byte {
	file_msgproto_msgdef_proto_rawDescOnce.Do(func() {
		file_msgproto_msgdef_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgproto_msgdef_proto_rawDescData)
	})
	return file_msgproto_msgdef_proto_rawDescData
}

var file_msgproto_msgdef_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgproto_msgdef_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msgproto_msgdef_proto_goTypes = []interface{}{
	(MsgType)(0), // 0: msg.MsgType
	(*Req)(nil),  // 1: msg.Req
	(*Res)(nil),  // 2: msg.Res
}
var file_msgproto_msgdef_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgproto_msgdef_proto_init() }
func file_msgproto_msgdef_proto_init() {
	if File_msgproto_msgdef_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgproto_msgdef_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_msgdef_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgproto_msgdef_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgproto_msgdef_proto_goTypes,
		DependencyIndexes: file_msgproto_msgdef_proto_depIdxs,
		EnumInfos:         file_msgproto_msgdef_proto_enumTypes,
		MessageInfos:      file_msgproto_msgdef_proto_msgTypes,
	}.Build()
	File_msgproto_msgdef_proto = out.File
	file_msgproto_msgdef_proto_rawDesc = nil
	file_msgproto_msgdef_proto_goTypes = nil
	file_msgproto_msgdef_proto_depIdxs = nil
}
