// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: rpcproto/rpcdef.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TestOne) Reset() {
	*x = TestOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_rpcdef_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOne) ProtoMessage() {}

func (x *TestOne) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_rpcdef_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOne.ProtoReflect.Descriptor instead.
func (*TestOne) Descriptor() ([]byte, []int) {
	return file_rpcproto_rpcdef_proto_rawDescGZIP(), []int{0}
}

func (x *TestOne) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TestOneRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TestOneRet) Reset() {
	*x = TestOneRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_rpcdef_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestOneRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOneRet) ProtoMessage() {}

func (x *TestOneRet) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_rpcdef_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOneRet.ProtoReflect.Descriptor instead.
func (*TestOneRet) Descriptor() ([]byte, []int) {
	return file_rpcproto_rpcdef_proto_rawDescGZIP(), []int{1}
}

func (x *TestOneRet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TestTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int32  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TestTwo) Reset() {
	*x = TestTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_rpcdef_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTwo) ProtoMessage() {}

func (x *TestTwo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_rpcdef_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTwo.ProtoReflect.Descriptor instead.
func (*TestTwo) Descriptor() ([]byte, []int) {
	return file_rpcproto_rpcdef_proto_rawDescGZIP(), []int{2}
}

func (x *TestTwo) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *TestTwo) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TestTwoRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int32  `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TestTwoRet) Reset() {
	*x = TestTwoRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_rpcdef_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTwoRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTwoRet) ProtoMessage() {}

func (x *TestTwoRet) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_rpcdef_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTwoRet.ProtoReflect.Descriptor instead.
func (*TestTwoRet) Descriptor() ([]byte, []int) {
	return file_rpcproto_rpcdef_proto_rawDescGZIP(), []int{3}
}

func (x *TestTwoRet) GetData() int32 {
	if x != nil {
		return x.Data
	}
	return 0
}

func (x *TestTwoRet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type TestThree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UList []uint64 `protobuf:"varint,1,rep,packed,name=UList,proto3" json:"UList,omitempty"`
}

func (x *TestThree) Reset() {
	*x = TestThree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_rpcdef_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestThree) ProtoMessage() {}

func (x *TestThree) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_rpcdef_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestThree.ProtoReflect.Descriptor instead.
func (*TestThree) Descriptor() ([]byte, []int) {
	return file_rpcproto_rpcdef_proto_rawDescGZIP(), []int{4}
}

func (x *TestThree) GetUList() []uint64 {
	if x != nil {
		return x.UList
	}
	return nil
}

var File_rpcproto_rpcdef_proto protoreflect.FileDescriptor

var file_rpcproto_rpcdef_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x64, 0x65,
	0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x1b, 0x0a, 0x07,
	0x54, 0x65, 0x73, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x73,
	0x74, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2f, 0x0a, 0x07, 0x54, 0x65, 0x73,
	0x74, 0x54, 0x77, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x32, 0x0a, 0x0a, 0x54, 0x65,
	0x73, 0x74, 0x54, 0x77, 0x6f, 0x52, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x21,
	0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x55,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x55, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpcproto_rpcdef_proto_rawDescOnce sync.Once
	file_rpcproto_rpcdef_proto_rawDescData = file_rpcproto_rpcdef_proto_rawDesc
)

func file_rpcproto_rpcdef_proto_rawDescGZIP() []byte {
	file_rpcproto_rpcdef_proto_rawDescOnce.Do(func() {
		file_rpcproto_rpcdef_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcproto_rpcdef_proto_rawDescData)
	})
	return file_rpcproto_rpcdef_proto_rawDescData
}

var file_rpcproto_rpcdef_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rpcproto_rpcdef_proto_goTypes = []interface{}{
	(*TestOne)(nil),    // 0: rpc.TestOne
	(*TestOneRet)(nil), // 1: rpc.TestOneRet
	(*TestTwo)(nil),    // 2: rpc.TestTwo
	(*TestTwoRet)(nil), // 3: rpc.TestTwoRet
	(*TestThree)(nil),  // 4: rpc.TestThree
}
var file_rpcproto_rpcdef_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcproto_rpcdef_proto_init() }
func file_rpcproto_rpcdef_proto_init() {
	if File_rpcproto_rpcdef_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcproto_rpcdef_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_rpcdef_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestOneRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_rpcdef_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_rpcdef_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTwoRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_rpcdef_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestThree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcproto_rpcdef_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpcproto_rpcdef_proto_goTypes,
		DependencyIndexes: file_rpcproto_rpcdef_proto_depIdxs,
		MessageInfos:      file_rpcproto_rpcdef_proto_msgTypes,
	}.Build()
	File_rpcproto_rpcdef_proto = out.File
	file_rpcproto_rpcdef_proto_rawDesc = nil
	file_rpcproto_rpcdef_proto_goTypes = nil
	file_rpcproto_rpcdef_proto_depIdxs = nil
}
